### ISSUE TITLE
Welcome to SEBC!

### ISSUE THREAD

**Issue by mfernest** [jmcasals/SEBC#1]
One problem with your current setup: please note you have two top-level directories (SEBC and SEBC-master). This probably comes from the directory structure you have in your local setup. Please make sure there is a single `SEBC/` directory at the top of your git repo. You can remove the `invalid` flag from this Issue once that is corrected.

Please remove the `incomplete` flag once `rsiwicki` has accepted your invitation to collaborate.

Finally, you may close this Issue once both conditions have been addressed.

**Comment by jmcasals** [comment]
already done. Waiting for  rsiwicki
