### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by jmcasals** [jmcasals/SEBC#3]

**Comment by jmcasals** [comment]
These labs will have you:
Replicate data to another cluster
Use teragen and terasort to benchmark performance
Test HDFS Snapshots
Enable NameNode HA configuratio

**Comment by jmcasals** [comment]
time hadoop jar /opt/cloudera/parcels/CDH-5.10.0-1.cdh5.10.0.p0.41/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen -D dfs.block.size=33554432 100000 /tmp/test_file
time hadoop jar /opt/cloudera/parcels/CDH-5.10.0-1.cdh5.10.0.p0.41/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar terasort  /tmp/test_file /tmp/test_file_sort

**Comment by mfernest** [comment]
INC
